version: '3'

services:
  db:
    image: postgres:17
    restart: always
    ports:
      - 5437:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: nannyDB
    volumes:
      - ./postgres:/var/lib/postgresql/data
